[build]
  command = "bundle install && bundle exec rails assets:precompile"
  publish = "public"

[build.environment]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[[redirects]]
  from = "/lookbook/*"
  to = "/lookbook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 